// Catálogo de productos de Level-Up Gamer.
// Cada producto tiene: id, nombre, categoría, precio (en CLP, sin puntos),
// stock y la URL de la imagen.

const productos = [
  {
    id: 1,
    nombre: 'Control Gamer Inalámbrico',
    categoria: 'Accesorios',
    precio: 59990,
    stock: 15,
    codigo: 'AC001',
    imagen: 'https://i5.walmartimages.cl/asr/f2dc7333-726e-46d4-9eed-e66de629fb61.9b79ad009e52a9b2e103d030d98c9160.jpeg',
    descripcion: 'Ofrece una experiencia de juego cómoda con botones mapeables y respuesta táctil mejorada. Compatible con consolas Xbox y PC.',
  },
  {
    id: 2,
    nombre: 'Auriculares HyperX Cloud II',
    categoria: 'Accesorios',
    precio: 79990,
    stock: 10,
    codigo: 'AC002',
    imagen: 'https://media.spdigital.cl/thumbnails/products/ruuqaor9_dac549f9_thumbnail_4096.jpg',
    descripcion: 'Sonido envolvente de calidad, micrófono desmontable y almohadillas de espuma viscoelástica para mayor comodidad.',
  },
  {
    id: 3,
    nombre: 'Mouse Logitech G502 HERO',
    categoria: 'Accesorios',
    precio: 49990,
    stock: 20,
    codigo: 'MS001',
    imagen: 'https://media.falabella.com/falabellaCL/156495581_01/w=1200,h=1200,fit=pad',
    descripcion: 'Sensor de alta precisión y botones personalizables, ideal para gamers que buscan control preciso.',
  },
  {
    id: 4,
    nombre: 'Mousepad Razer Goliathus Extended',
    categoria: 'Accesorios',
    precio: 29990,
    stock: 25,
    codigo: 'MP001',
    imagen: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR10h795ngPs0Vf3x94aZLNo9I2ZxarYuIRkjIE0aKIHzke8DAb90xHa7M093Vy3VAeokY4-v18_SzhBokVJ9HdPHyqBs6ZhVQhXI9VmdSZZY4s6BUL89n0',
    descripcion: 'Área de juego amplia con iluminación RGB personalizable y superficie suave para el movimiento del mouse.',
  },
  {
    id: 5,
    nombre: 'Consola PlayStation 5',
    categoria: 'Consolas',
    precio: 549990,
    stock: 5,
    codigo: 'CO001',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-SpQ9c7n4ZDaBkZz-pKy0NEswPV7iu_tCZMV7c2kljw&s',
    descripcion: 'La consola de última generación de Sony, con gráficos impresionantes y tiempos de carga ultrarrápidos.',
  },
  {
    id: 6,
    nombre: 'Silla Gamer Secretlab Titan',
    categoria: 'Sillas',
    precio: 349990,
    stock: 8,
    codigo: 'SG001',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5WmcwZr4f2avB3ZdZbVimkHRhSs7uNbSLRHnQMB5Lzg&s=10',
    descripcion: 'Máximo confort con soporte ergonómico y ajustes personalizables para sesiones de juego prolongadas.',
  },
  {
    id: 7,
    nombre: "Polera Gamer Personalizada 'Level-Up'",
    categoria: 'Vestuario',
    precio: 14990,
    stock: 30,
    codigo: 'PP001',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv3XixjADXXicAg9AHDnWwum48WguHtPI_cU6NZQ7XOQ&s=10',
    descripcion: 'Camiseta cómoda y estilizada, personalizable con tu gamer tag o diseño favorito.',
  },
  {
    id: 8,
    nombre: 'Catan (juego de mesa)',
    categoria: 'Juegos de Mesa',
    precio: 29990,
    stock: 12,
    codigo: 'JM001',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2WnrovxaRwBhbW4MiBUX1IyWvIo2qAvAf7m_sYHeXHw&s=10',
    descripcion: 'Clásico juego de estrategia donde los jugadores compiten por colonizar la isla de Catan. Para 3-4 jugadores.',
  },
  {
    id: 9,
    nombre: 'Carcassonne (juego de mesa)',
    categoria: 'Juegos de Mesa',
    precio: 24990,
    stock: 14,
    codigo: 'JM002',
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbEtJm-tmJgbMtByrwgnuRm97Rdul-D4GqLQbuZ7N6kA&s=10',
    descripcion: 'Juego de colocación de fichas donde los jugadores construyen el paisaje medieval. Para 2-5 jugadores.',
  },
  {
    id: 10,
    nombre: 'PC Gamer ASUS ROG Strix',
    categoria: 'Computadores',
    precio: 1299990,
    stock: 3,
    codigo: 'CG001',
    imagen: 'https://media.falabella.com/falabellaCL/80719928_01/w=1200,h=1200,fit=pad',
    descripcion: 'Potencia y rendimiento de última generación para correr tus juegos en máxima calidad. Ideal para streaming.',
  },
]

export default productos